/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class'],
  theme: {
    extend: {
      fontFamily: {
        sans: 'var(--font-inter)',
        alt: 'var(--font-space-grotesk)',
      },
      colors: {
        rosePineMoon: {
          base: '#232136',
          surface: '#2a273f',
          overlay: '#393552',
          muted: '#6e6a86',
          subtle: '#908caa',
          text: '#e0def4',
          love: '#eb6f92',
          gold: '#f6c177',
          rose: '#ea9a97',
          pine: '#3e8fb0',
          foam: '#9ccfd8',
          iris: '#c4a7e7',
          highlightLow: '#2a283e',
          highlightMed: '#44415a',
          highlightHigh: '#56526e',
        },
        rosePineDawn: {
          base: '#faf4ed',
          surface: '#fffaf3',
          overlay: '#f2e9e1',
          muted: '#9893a5',
          subtle: '#797593',
          text: '#575279',
          love: '#b4637a',
          gold: '#ea9d34',
          rose: '#d7827e',
          pine: '#286983',
          foam: '#56949f',
          iris: '#907aa9',
          highlightLow: '#f4ede8',
          highlightMed: '#dfdad9',
          highlightHigh: '#cecacd',
        },
      },
      typography: ({ theme }) => ({
        rosePine: {
          css: {
            '--tw-prose-body': theme('colors.rosePineDawn.text'),
            '--tw-prose-headings': theme('colors.rosePineDawn.text'),
            '--tw-prose-links': theme('colors.rosePineDawn.iris'),
            '--tw-prose-bold': theme('colors.rosePineDawn.iris'),
            '--tw-prose-bullets': theme('colors.rosePineDawn.iris'),
            '--tw-prose-counters': theme('colors.rosePineDawn.iris'),
            '--tw-prose-hr': theme('colors.rosePineDawn.highlightMed'),
            '--tw-prose-quotes': theme('colors.rosePineDawn.text'),
            '--tw-prose-quote-borders': theme(
              'colors.rosePineDawn.highlightMed',
            ),
            '--tw-prose-captions': theme('colors.rosePineDawn.highlightHigh'),
            '--tw-prose-pre-bg': theme('colors.rosePineDawn.surface'),
            '--tw-prose-th-borders': theme('colors.rosePineDawn.highlightMed'),
            '--tw-prose-td-borders': theme('colors.rosePineDawn.highlightMed'),
            '--tw-prose-invert-body': theme('colors.rosePineMoon.text'),
            '--tw-prose-invert-headings': theme('colors.rosePineMoon.text'),
            '--tw-prose-invert-links': theme('colors.rosePineMoon.iris'),
            '--tw-prose-invert-bold': theme('colors.rosePineMoon.iris'),
            '--tw-prose-invert-bullets': theme('colors.rosePineMoon.iris'),
            '--tw-prose-invert-counters': theme('colors.rosePineMoon.iris'),
            '--tw-prose-invert-hr': theme('colors.rosePineMoon.highlightMed'),
            '--tw-prose-invert-quotes': theme('colors.rosePineMoon.text'),
            '--tw-prose-invert-quote-borders': theme(
              'colors.rosePineMoon.highlightMed',
            ),
            '--tw-prose-invert-captions': theme(
              'colors.rosePineMoon.highlightHigh',
            ),
            '--tw-prose-invert-pre-bg': theme('colors.rosePineMoon.surface'),
            '--tw-prose-invert-th-borders': theme(
              'colors.rosePineMoon.highlightMed',
            ),
            '--tw-prose-invert-td-borders': theme(
              'colors.rosePineMoon.highlightMed',
            ),
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
