import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Space_Grotesk as SpaceGrotesk } from 'next/font/google'
import { Providers } from '@/components/Providers'

const spaceGrotesk = SpaceGrotesk({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-space-grotesk',
})
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Devnook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers attribute="class" defaultTheme="system" enableSystem>
        <body
          className={`${inter.variable} ${spaceGrotesk.variable} bg-rosePineDawn-base font-sans text-rosePineDawn-text transition-all dark:bg-rosePineMoon-base dark:text-rosePineMoon-text`}
        >
          <main className="mx-auto min-h-screen max-w-3xl px-12">
            <Header />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
